spring:
  application:
    name: todo
  datasource:
    url: ${DB_URL:jdbc:sqlserver://127.0.0.1:1433;databaseName=todo;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:verYs3cret}
  flyway:
    enabled: true
    flyway:
    url: ${DB_URL:jdbc:sqlserver://127.0.0.1:1433;trustServerCertificate=true}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:verYs3cret}
    validate-on-migrate: true
    baseline-on-migrate: true
